# using a custom image that already has
# the required packages installed in renv's library
# (this considerably speeds up the CI pipeline)
image: liseb/custom-renv-install

# for clarity, this is the paths (in the container)
# that contain renv's cache and library folders :
variables:
  RENV_PATHS_CACHE: "/home/workspace/.renv/cache"
  RENV_PATHS_LIBRARY: "/home/workspace/.renv/library"

# rules template :
# run on merge request or commit on master
.custom_rules: &rules_definition
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - build
  - check
  - make

build-package:
  stage: build
  <<: *rules_definition
  script:
    - echo "build stage !!"
    - Rscript -e 'print(renv::paths$library())'
    - Rscript -e 'devtools::build()'

check-package:
  stage: check
  <<: *rules_definition
  script:
    - echo "Checking package and running tests..."
    - Rscript -e 'devtools::check(error_on = "error")'

make-pipeline:
  stage: make
  <<: *rules_definition
  script:
    - echo "Making the pipeline"
    - Rscript -e 'source(here::here("utils/write_test_data.R"))'
    - Rscript -e 'tinytex::reinstall_tinytex(force = T)'
    - Rscript -e 'source("make.R")'
  dependencies:
    - check-package
  artifacts:
    when: always
    paths:
      - data/test
      - outputs/test/pdf
    expire_in: 1 day

# ideas for other possible stages :
# - build documentation and deploy it somewhere
# - code coverage with covr
